---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install apache
    apt: name=apache2 state=latest
  - name: Ensure apache is running
    service: name=apache2 state=started enabled=yes
  - name: Install mysql
    apt: name=mysql-server state=latest
  - name: Ensure mysql is running
    service: name=mysql state=started enabled=yes
  handlers:
  - name: Restart apache
    service: name=apache2 state=restarted