---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: No password sudo
    lineinfile: 
      dest: /etc/sudoers
      regexp: '^%sudo'
      line: '%sudo   ALL=(ALL) NOPASSWD: ALL'
  - name: Legacy SSH client Kex
    lineinfile: 
      dest: /etc/ssh/sshd_config
      line: 'KexAlgorithms diffie-hellman-group-exchange-sha256,diffie-hellman-group1-sha1'
  - name: Legacy SSH client Ciphers
    lineinfile: 
      dest: /etc/ssh/sshd_config
      line: 'Ciphers aes128-cbc'
  - name: Install apache
    apt: name=apache2 state=latest
  - name: Install misc dev tools
    apt: name={{ item }} state=present
    with_items:
      - curl
      - git
      - rsync
      - gcc
      - g++
      - make
      - bzip2
      - unzip
      - libssl-dev
      - vim
      - lynx
      - build-essential
      - libxml2-dev
      - libbz2-dev
      - telnet
      - imagemagick
      - samba
      - exim4-base
      - ruby
      - ruby-dev
  - name: Configure apache user
    user:
      name: www-data
      shell: /bin/bash
      password: '$6$DoDsDeMSxK4L$d5Tk6NX1N5kxmmQn73Zceg1lQQ7JUKeueHJN3kRVE2zTWD5f8mQH4jSnK/dNR24svbIXQLC66MWgPBL7.5gJ..'
      groups: www-data,sudo
      append: yes
  - name: Apache home
    file:
      path: /var/www
      state: directory
      owner: www-data
      group: www-data
  - name: Apache desktop
    file:
      path: /var/www/Desktop
      state: directory
      owner: www-data
      group: www-data
  - name: Html folder
    file:
      path: /var/www/html
      state: directory
      owner: www-data
      group: www-data
  - name: Conf.d folder
    file:
      path: /var/www/html/conf.d
      state: directory
      owner: www-data
      group: www-data
  - name: Enable virtual hosts
    copy:
      src: files/apache.conf
      dest: /etc/apache2/conf-enabled/apache.conf
      owner: root
      group: root
      mode: 0644
  - name: Virtual host example
    copy:
      src: files/example.com.conf
      dest: /var/www/html/conf.d/example.com.conf
      owner: www-data
      group: www-data
      mode: 0754
  - name: Ensure apache is running
    service: name=apache2 state=started enabled=yes
  - name: Install php
    apt: name={{ item }} state=latest
    with_items:
      - php
      - php-mcrypt
      - php-curl
      - php-mysql
      - php-cli
      - php-memcache
      - php-memcached
      - php-db
      - php-gd
      - php-imap
      - php-dev
      - phpunit
      - php-pear
      - php-xdebug
      - php-xmlrpc
      - libapache2-mod-php7.0
  - name: Install composer
    shell: '/usr/bin/curl -sS https://getcomposer.org/installer | HOME=/var/www php -- --install-dir=/usr/bin --filename=composer'
    args:
      creates: /usr/bin/composer
  - name: Install mysql
    apt: name=mysql-server state=latest
  - name: Ensure mysql is running
    service: name=mysql state=started enabled=yes
  - name: Install mysql workbench
    apt: name=mysql-workbench state=latest
  - name: Install Sublime 3
    shell: '/usr/bin/wget https://download.sublimetext.com/sublime-text_build-3126_amd64.deb && mv sublime-* sublime.deb && /usr/bin/dpkg -i sublime.deb'
    args:
      chdir: /usr/src
      creates: /usr/src/sublime.deb
  - name: Install php storm IDE
    become_user: www-data
    shell: '/usr/bin/wget https://download.jetbrains.com/webide/PhpStorm-2016.3.1.tar.gz && tar -zxf PhpStorm-2016.3.1.tar.gz && rm *.tar.gz && mv PhpStorm* PhpStorm'
    args:
      chdir: /tmp
      creates: /tmp/PhpStorm
  - name: PhpStorm shortcut
    copy:
      src: files/phpstorm.desktop
      dest: /var/www/Desktop/phpstorm.desktop
      owner: www-data
      group: www-data
      mode: 0755
  - name: Exim config
    lineinfile: 
      dest: /etc/exim4/update-exim4.conf.conf
      regexp: "^dc_eximconfig_configtype='local'"
      line: "dc_eximconfig_configtype='internet'"
  - name: Update Exim
    shell: '/usr/sbin/update-exim4.conf > /var/log/exim-updated.log'
    args:
      creates: /var/log/exim-updated.log
#  - name: Samba service
#    service: name=samba state=started enabled=yes
  - name: Samba share for www-data
    shell: '/bin/echo -ne "www-data\nwww-data\n" | smbpasswd -a -s www-data >> /var/log/smbpasswd.log'
    args:
      creates: /var/log/smbpasswd.log
  - name: Samba config file
    copy:
      src: files/smb.conf
      dest: /etc/samba/smb.conf
      owner: root
      group: root
      mode: 0644
  - name: Node source
    shell: '/usr/bin/curl -sL https://deb.nodesource.com/setup_6.x | /bin/bash -'
    args:
      creates: /etc/apt/sources.list.d/nodesource.list
  - name: Install node
    apt: name=nodejs state=latest
  - name: Node modules
    shell: '/usr/bin/npm install --global npm gulp gulp-cli bower grunt grunt-cli yo generator-angular'
    args:
      creates: /usr/bin/grunt
  - name: Install sass and compass
    shell: '/usr/bin/gem install sass --version 3.4.20 && /usr/bin/gem install compass'
    args:
      creates: /usr/local/bin/sass
  handlers:
  - name: Restart apache
    service: name=apache2 state=restarted